// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gdi_ButtonXL.h"

/////////////////////////////////////////////////////////////////////////////
// CGdi_ButtonXL

IMPLEMENT_DYNCREATE(CGdi_ButtonXL, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGdi_ButtonXL properties

/////////////////////////////////////////////////////////////////////////////
// CGdi_ButtonXL operations
