#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGdi_ButtonXL wrapper class

class CGdi_ButtonXL : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGdi_ButtonXL)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7F078F87, 0x2F90, 0x4A93, { 0xA0, 0x93, 0xA5, 0x19, 0xF6, 0xC5, 0x45, 0xDC } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
	}

// Attributes
public:


// Operations
public:

// _DGDIButtonXL

// Functions
//

	void AboutBox()
	{
		InvokeHelper(DISPID_ABOUTBOX, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	void SetLight(BOOL Light)
	{
		static BYTE parms[] = VTS_BOOL ;
		InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms, Light);
	}

// Properties
//

long GetBitMapSelect()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}
void SetBitMapSelect(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}
long GetFontSize()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}
void SetFontSize(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}
unsigned long GetTextColor()
{
	unsigned long result;
	GetProperty(0x4, VT_UI4, (void*)&result);
	return result;
}
void SetTextColor(unsigned long propVal)
{
	SetProperty(0x4, VT_UI4, propVal);
}
BOOL GetLightOn()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}
void SetLightOn(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}
long GetTextOffset1()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}
void SetTextOffset1(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}
long GetTextOffset2()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}
void SetTextOffset2(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}
void SetTitleText1(CString propVal)
{
	SetProperty(0x8, VT_BSTR, propVal);
}
void SetTitleText2(CString propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

};
