// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gdigagetctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CGdigagetctrl1

IMPLEMENT_DYNCREATE(CGdigagetctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGdigagetctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CGdigagetctrl1 operations
