// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gdimotorstatusctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CGdimotorstatusctrl1

IMPLEMENT_DYNCREATE(CGdimotorstatusctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGdimotorstatusctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CGdimotorstatusctrl1 operations
