// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gdistatusboxctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CGdistatusboxctrl1

IMPLEMENT_DYNCREATE(CGdistatusboxctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGdistatusboxctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CGdistatusboxctrl1 operations
